name: Go Test
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test

